// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TresManos.Backend.Data;

#nullable disable

namespace TresManos.Backend.Migrations
{
    [DbContext(typeof(JuegoDbContext))]
    partial class JuegoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TresManos.Shared.Entities.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartidaId"));

                    b.Property<bool>("EsRevancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAceptacionRevancha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("GanadorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("PartidaOriginalId")
                        .HasColumnType("int");

                    b.Property<int?>("PerdedorUsuarioId")
                        .HasColumnType("int");

                    b.Property<bool?>("RevanchaAceptadaPorPerdedor")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId_Jugador1")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId_Jugador2")
                        .HasColumnType("int");

                    b.HasKey("PartidaId");

                    b.HasIndex("GanadorUsuarioId");

                    b.HasIndex("PartidaOriginalId");

                    b.HasIndex("PerdedorUsuarioId");

                    b.HasIndex("UsuarioId_Jugador1");

                    b.HasIndex("UsuarioId_Jugador2");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Ronda", b =>
                {
                    b.Property<int>("RondaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RondaId"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("GanadorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("MovimientoJugador1")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MovimientoJugador2")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("NumeroRonda")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int?>("PerdedorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("RondaId");

                    b.HasIndex("GanadorUsuarioId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("PerdedorUsuarioId");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Partida", b =>
                {
                    b.HasOne("TresManos.Shared.Entities.Usuario", "Ganador")
                        .WithMany("PartidasGanadas")
                        .HasForeignKey("GanadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TresManos.Shared.Entities.Partida", "PartidaOriginal")
                        .WithMany("Revanchas")
                        .HasForeignKey("PartidaOriginalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TresManos.Shared.Entities.Usuario", "Perdedor")
                        .WithMany("PartidasPerdidas")
                        .HasForeignKey("PerdedorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TresManos.Shared.Entities.Usuario", "Jugador1")
                        .WithMany("PartidasComoJugador1")
                        .HasForeignKey("UsuarioId_Jugador1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TresManos.Shared.Entities.Usuario", "Jugador2")
                        .WithMany("PartidasComoJugador2")
                        .HasForeignKey("UsuarioId_Jugador2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");

                    b.Navigation("PartidaOriginal");

                    b.Navigation("Perdedor");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Ronda", b =>
                {
                    b.HasOne("TresManos.Shared.Entities.Usuario", "GanadorUsuario")
                        .WithMany("RondasGanadas")
                        .HasForeignKey("GanadorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TresManos.Shared.Entities.Partida", "Partida")
                        .WithMany("Rondas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TresManos.Shared.Entities.Usuario", "PerdedorUsuario")
                        .WithMany("RondasPerdidas")
                        .HasForeignKey("PerdedorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GanadorUsuario");

                    b.Navigation("Partida");

                    b.Navigation("PerdedorUsuario");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Partida", b =>
                {
                    b.Navigation("Revanchas");

                    b.Navigation("Rondas");
                });

            modelBuilder.Entity("TresManos.Shared.Entities.Usuario", b =>
                {
                    b.Navigation("PartidasComoJugador1");

                    b.Navigation("PartidasComoJugador2");

                    b.Navigation("PartidasGanadas");

                    b.Navigation("PartidasPerdidas");

                    b.Navigation("RondasGanadas");

                    b.Navigation("RondasPerdidas");
                });
#pragma warning restore 612, 618
        }
    }
}
